# Generated by Django 4.1.7 on 2023-03-22 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedule_wagtail", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BuyCalendarandHour",
        ),
    ]
