# Generated by Django 4.1.7 on 2023-04-04 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedule_wagtail", "0006_calendarpagereceptionist_calendarpagevet_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calendarpagereceptionist",
            name="coderedpage_ptr",
        ),
        migrations.RemoveField(
            model_name="calendarpagevet",
            name="coderedpage_ptr",
        ),
        migrations.DeleteModel(
            name="CalendarPageClient",
        ),
        migrations.DeleteModel(
            name="CalendarPageReceptionist",
        ),
        migrations.DeleteModel(
            name="CalendarPageVet",
        ),
    ]
