# Generated by Django 4.1.7 on 2023-04-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("veter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
