# Generated by Django 4.1.7 on 2023-04-04 10:52

from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.routable_page.models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_initial_data"),
        ("veter", "0002_alter_visit_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="PetPage",
            fields=[
                (
                    "webpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="website.webpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "PetPage",
            },
            bases=(
                wagtail.contrib.routable_page.models.RoutablePageMixin,
                "website.webpage",
            ),
        ),
        migrations.AlterModelOptions(
            name="recepjonistpage",
            options={"verbose_name": "RecepjonistPage"},
        ),
        migrations.AlterModelOptions(
            name="vetpage",
            options={"verbose_name": "VetPage"},
        ),
    ]
