# Generated by Django 4.1.3 on 2023-03-08 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_initial_data'),
        ('veter', '0002_pet_description_result_pet_alter_pet_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VetForm',
            fields=[
                ('formpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.formpage')),
            ],
            options={
                'verbose_name': 'Vet Form',
            },
            bases=('website.formpage',),
        ),
    ]
