# Generated by Django 4.1.3 on 2023-03-18 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('veter', '0003_vetform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recepc',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Recepc',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Wet',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Wet',
            },
            bases=('wagtailcore.page',),
        ),
    ]
