# Generated by Django 4.1.3 on 2023-03-18 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_initial_data'),
        ('wagtailcore', '0083_workflowcontenttype'),
        ('veter', '0004_recepc_wet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VetForm',
            new_name='BuyCalendarandHour',
        ),
        migrations.RenameModel(
            old_name='Recepc',
            new_name='RecepjonistPage',
        ),
        migrations.RenameModel(
            old_name='Wet',
            new_name='VetPage',
        ),
    ]
