# Generated by Django 4.1.3 on 2023-03-20 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veter', '0005_rename_vetform_buycalendarandhour_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buycalendarandhour',
            options={'verbose_name': 'CodeRed Form Page'},
        ),
    ]
