# Generated by Django 4.1.7 on 2023-04-06 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0014_use_autofields_for_pk"),
        ("veter", "0005_alter_calendarpageclient_body_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visit",
            name="cost",
        ),
        migrations.RemoveField(
            model_name="visit",
            name="date",
        ),
        migrations.RemoveField(
            model_name="visit",
            name="description",
        ),
        migrations.RemoveField(
            model_name="visit",
            name="id",
        ),
        migrations.RemoveField(
            model_name="visit",
            name="type",
        ),
        migrations.AddField(
            model_name="visit",
            name="event_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="schedule.event",
            ),
            preserve_default=False,
        ),
    ]
