# Generated by Django 3.2.18 on 2023-03-20 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veter', '0006_alter_buycalendarandhour_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buycalendarandhour',
            options={'verbose_name': 'calendar'},
        ),
    ]
