# Generated by Django 4.1.7 on 2023-04-07 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("veter", "0006_remove_visit_cost_remove_visit_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="Client",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"groups__name": "Vet"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Client",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="vet",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"groups__name": "Clients"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vet",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
