# Generated by Django 4.1.7 on 2023-04-12 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("veter", "0007_visit_client_alter_visit_vet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visit",
            name="Client",
        ),
        migrations.AddField(
            model_name="visit",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pet",
            name="Client",
            field=models.ForeignKey(
                default=1,
                limit_choices_to={"groups__name": "Clients"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="visit",
            name="animal",
            field=modelcluster.fields.ParentalKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Visit",
                to="veter.pet",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="visit",
            name="vet",
            field=models.ForeignKey(
                limit_choices_to={"groups__name": "Clients"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vet",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
