# Generated by Django 3.2.18 on 2023-03-20 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderedcms', '0035_remove_googleapisettings_site_and_more'),
        ('wagtailcore', '0083_workflowcontenttype'),
        ('wagtailforms', '0005_alter_formsubmission_form_data'),
        ('website', '0002_initial_data'),
        ('wagtailredirects', '0008_add_verbose_name_plural'),
        ('veter', '0007_alter_buycalendarandhour_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuyCalendarandHour',
        ),
    ]
