# Generated by Django 4.1.7 on 2023-04-01 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("veter", "0008_delete_buycalendarandhour"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pet",
            old_name="gender",
            new_name="isfemale",
        ),
        migrations.AddField(
            model_name="pet",
            name="Client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="treatment",
            name="pet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="veter.pet",
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="animal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="veter.pet",
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="vet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
