# Generated by Django 4.1.7 on 2023-06-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("veter", "0009_alter_pet_options_alter_result_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treatment",
            name="date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="data"),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="text",
            field=models.CharField(max_length=255, verbose_name="tekst"),
        ),
    ]
