# Generated by Django 4.1.7 on 2023-06-13 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("veter", "0014_result_date_treatment_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="treatment",
            name="date",
        ),
    ]
