# Generated by Django 4.1.7 on 2023-06-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("veter", "0015_remove_treatment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatment",
            name="date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="data"),
        ),
    ]
